### ISSUE TITLE
Unable to install pip3 install -r requirements.txt

### ISSUE THREAD

**Issue by aravindb26** [ihebski/DefaultCreds-cheat-sheet#37]
Hi, I'm unable to install requirements.txt.

It's showing some error

× python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [30 lines of output]
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "/tmp/pip-install-vn9do36r/hashlib_613de39c63484668ad3e7e574a224a1a/setup.py", line 68
          print "unknown OS, please update setup.py"
                ^
      SyntaxError: Missing parentheses in call to 'print'. Did you mean print("unknown OS, please update setup.py")?
      Error in sys.excepthook:
      Traceback (most recent call last):
        File "/usr/lib/python3/dist-packages/apport_python_hook.py", line 72, in apport_excepthook
          from apport.fileutils import likely_packaged, get_recent_crashes
        File "/usr/lib/python3/dist-packages/apport/__init__.py", line 5, in <module>
          from apport.report import Report
        File "/usr/lib/python3/dist-packages/apport/report.py", line 21, in <module>
          from urllib.request import urlopen
        File "/usr/lib/python3.8/urllib/request.py", line 87, in <module>
          import hashlib
        File "/tmp/pip-install-vn9do36r/hashlib_613de39c63484668ad3e7e574a224a1a/hashlib.py", line 80
          raise ValueError, "unsupported hash type"
                          ^
      SyntaxError: invalid syntax

      Original exception was:
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "/tmp/pip-install-vn9do36r/hashlib_613de39c63484668ad3e7e574a224a1a/setup.py", line 68
          print "unknown OS, please update setup.py"
                ^
      SyntaxError: Missing parentheses in call to 'print'. Did you mean print("unknown OS, please update setup.py")?
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.

**Comment by ihebski** [comment]
I guess you don't need to install hashlib from requirements.txt, try to run creds script without installing any package `python3 creds search tomcat` .
Could you please share the os name and python version ?

**Comment by ihebski** [comment]
hashlib removed from the requirement file, it should works fine without any issue.
Thanks :)
