### ISSUE TITLE
Error when trying to update on Windows

### ISSUE THREAD

**Issue by ILPlais** [ihebski/DefaultCreds-cheat-sheet#65]
Hello,
I had installed DefaultCreds. But when I'm trying to update the database, I've got an error message about the temporary folder.
Here is the error:
```
PS C:\> creds update
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "C:\Python312\Scripts\creds.exe\__main__.py", line 7, in <module>
  File "C:\Python312\Lib\site-packages\DefaultCreds\creds.py", line 127, in run
    fire.Fire()
  File "C:\Python312\Lib\site-packages\fire\core.py", line 141, in Fire
    component_trace = _Fire(component, args, parsed_flag_args, context, name)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python312\Lib\site-packages\fire\core.py", line 475, in _Fire
    component, remaining_args = _CallAndUpdateTrace(
                                ^^^^^^^^^^^^^^^^^^^^
  File "C:\Python312\Lib\site-packages\fire\core.py", line 691, in _CallAndUpdateTrace
    component = fn(*varargs, **kwargs)
                ^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python312\Lib\site-packages\DefaultCreds\creds.py", line 122, in update
    get_db('/tmp',"Check for new updates...🔍")
  File "C:\Python312\Lib\site-packages\DefaultCreds\creds.py", line 35, in get_db
    db = TinyDB(f"{path}/DefaultCreds_db.json",storage=CachingMiddleware(JSONStorage))
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python312\Lib\site-packages\tinydb\database.py", line 94, in __init__
    self._storage: Storage = storage(*args, **kwargs)
                             ^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python312\Lib\site-packages\tinydb\middlewares.py", line 63, in __call__
    self.storage = self._storage_cls(*args, **kwargs)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python312\Lib\site-packages\tinydb\storages.py", line 113, in __init__
    touch(path, create_dirs=create_dirs)
  File "C:\Python312\Lib\site-packages\tinydb\storages.py", line 32, in touch
    with open(path, 'a'):
         ^^^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: '/tmp/DefaultCreds_db.json'
```
Is there a way to fix that?

**Comment by ihebski** [comment]
code updated on [pypi](https://pypi.org/project/DefaultCreds-cheat-sheet/), please reinstall and retest the package. Thanks
